Binary_Tree< Item_Type > Class Template Reference
#include <Binary_Tree.h>
Public Member Functions
Binary_Tree ()
Binary_Tree (const Item_Type &the_data, const Binary_Tree< Item_Type > &left_child=Binary_Tree(), const Binary_Tree< Item_Type > &right_child=Binary_Tree())
virtual ~Binary_Tree ()
Binary_Tree< Item_Type > get_left_subtree () const
Binary_Tree< Item_Type > get_right_subtree () const
const Item_Type & get_data () const
void set_data (Item_Type &data) const
bool is_null () const
bool is_leaf () const
virtual std::string to_string () const
std::string root_to_string () const
BTNode< Item_Type > * getRoot ()
void setRoot (BTNode< Item_Type > *node)
Static Public Member Functions
static Binary_Tree< Item_Type > read_binary_tree (std::istream &in)
Protected Member Functions
Binary_Tree (BTNode< Item_Type > *new_root)
Protected Attributes
BTNode< Item_Type > * root
Detailed Description
template<typename Item_Type>
class Binary_Tree< Item_Type >
Class for a binary tree.
Constructor & Destructor Documentation
Binary_Tree() [1/3]
template<typename Item_Type >
Binary_Tree< Item_Type >::Binary_Tree () [inline]
Construct an empty Binary_Tree.
Binary_Tree() [2/3]
template<typename Item_Type >
Binary_Tree< Item_Type >::Binary_Tree (const Item_Type & the_data, const Binary_Tree< Item_Type > & left_child = Binary_Tree< Item_Type >(), const Binary_Tree< Item_Type > & right_child = Binary_Tree< Item_Type >()) [inline]
Construct a Binary_Tree with two subtrees.
Parameters
the_data The data at the root
left_child The left subtree
right_child The right subtree
 Binary_Tree()
template<typename Item_Type >
virtual Binary_Tree< Item_Type >::~Binary_Tree () [inline], [virtual]
Virtual destructor to avoid warnings
Binary_Tree() [3/3]
template<typename Item_Type >
Binary_Tree< Item_Type >::Binary_Tree (BTNode< Item_Type > * new_root) [inline], [protected]
Construct a Binary_Tree with a given treeNode as the root
Member Function Documentation
get_data()
template<typename Item_Type >
const Item_Type & Binary_Tree< Item_Type >::get_data
Return the data field of the root.
Exceptions
std::invalid_argument if empty tree
Return data of this tree
Referenced by MorseCode::decode().
get_left_subtree()
template<typename Item_Type >
Binary_Tree< Item_Type > Binary_Tree< Item_Type >::get_left_subtree
Return the left subtree.
Return a left subtree of this tree
Referenced by MorseCode::addNodeBT(), and MorseCode::decode().
get_right_subtree()
template<typename Item_Type >
Binary_Tree< Item_Type > Binary_Tree< Item_Type >::get_right_subtree
Return the right subtree.
Return a right subtree of this tree
Referenced by MorseCode::addNodeBT(), and MorseCode::decode().
getRoot()
template<typename Item_Type >
BTNode< Item_Type > * Binary_Tree< Item_Type >::getRoot
returns the root node
Return data of this tree
Referenced by MorseCode::addNodeBT().
is_leaf()
template<typename Item_Type >
bool Binary_Tree< Item_Type >::is_leaf
Indicate that this tree is a leaf.
Return leaf node of this tree
is_null()
template<typename Item_Type >
bool Binary_Tree< Item_Type >::is_null
Indicate that this is the empty tree.
Return if tree is null
Referenced by MorseCode::addNodeBT().
read_binary_tree()
template<typename Item_Type >
Binary_Tree< Item_Type > Binary_Tree< Item_Type >::read_binary_tree (std::istream & in) [static]
Read a binary tree
Referenced by operator>>().
root_to_string()
template<typename Item_Type >
std::string Binary_Tree< Item_Type >::root_to_string () const [inline]
Return a string representation of the root
References Binary_Tree< Item_Type >::root.
set_data()
template<typename Item_Type >
void Binary_Tree< Item_Type >::set_data (Item_Type & data) const
Set the data field of the root.
Referenced by MorseCode::addNodeBT().
setRoot()
template<typename Item_Type >
void Binary_Tree< Item_Type >::setRoot (BTNode< Item_Type > * node)
set the root node
sets data of this tree
Referenced by MorseCode::addNodeBT().
to_string()
template<typename Item_Type >
std::string Binary_Tree< Item_Type >::to_string [virtual]
Return a string representation of this tree.
Return a string representation of this tree
Referenced by operator<<().
Member Data Documentation
root
template<typename Item_Type >
BTNode<Item_Type>* Binary_Tree< Item_Type >::root [protected]
Referenced by Binary_Tree< Item_Type >::root_to_string().
The documentation for this class was generated from the following file:
Binary_Tree.h