MorseCode Class Reference
#include <MorseCode.h>
Public Member Functions
MorseCode ()
Constructor taking no param.
void mapMorseCode ()
void encodeMessage (std::string &message)
void decodeMorseCode (const std::string &morseCode)
Private Member Functions
BTNode< char > * addNodeBT (char alphabet, const std::string &codePath, unsigned int index, Binary_Tree< char > *rootTree)
void decode (const std::string &morseCodeLetter, unsigned int index, Binary_Tree< char > *rootTree)
void checkMessageForErrors (const std::string &message)
void checkMorseCodeForErrors (const std::string &morseCodeMessage)
Private Attributes
Binary_Tree< char > * binaryTree
BinaryTree pointer object.
std::unordered_map< char, std::string > morseCodeMap
unordered map variable to contain mapped morse code and alphabet values.
Detailed Description
 Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: Class is a user-defined data type, which holds its own data members and member functions, which can be accessed and used by creating an instance of that class. Defining variables, methods and constructor.
Constructor & Destructor Documentation
MorseCode()
MorseCode::MorseCode ()
Constructor taking no param.
Postcondition
Post Condition - initialized binary tree.
Bug
Bug no known bug
object MorseCode::binaryTree is initialized in the constructor.
References binaryTree.
Member Function Documentation
addNodeBT()
BTNode< char > * MorseCode::addNodeBT (char alphabet, const std::string & codePath, unsigned int index, Binary_Tree< char > * rootTree) [private]
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function sets the data of the node in the binary tree after traversing to the right position using morse code
Parameters
 in alphabet
 in codePath
 in index
 in rootTree
Returns
[out] BTNode<char>
Precondition
Pre Condition - a char containing alphabet, a string containing morse code, an index and a binary tree is passed
Postcondition
Post Condition - binary tree is filled with values.
Bug
Bug No known bugs
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function sets the data of the node in the binary tree after traversing to the right position using morse code
Parameters
 in alphabet
 in codePath
 in index
 in rootTree
Returns
[out] BTNode<char>
Precondition
Pre Condition - a char containing alphabet, a string containing morse code, an index and a binary tree is passed
Postcondition
Post Condition - binary tree is filled with values.
Bug
Bug No known bugs
checking if the root node is null or not
creating a root node in the binary tree
traverse to left tree is '.' is encountered
storing the left subtree into a variable
assigning left node of root a new subtree
traverse to left tree is '-' is encountered
storing the right subtree into a variable
assigning right node of root a new subtree
else set the data of the node
set set the alphabet to the node data
return the node
References addNodeBT(), Binary_Tree< Item_Type >::get_left_subtree(), Binary_Tree< Item_Type >::get_right_subtree(), Binary_Tree< Item_Type >::getRoot(), Binary_Tree< Item_Type >::is_null(), Binary_Tree< Item_Type >::set_data(), and Binary_Tree< Item_Type >::setRoot().
Referenced by addNodeBT(), and mapMorseCode().
checkMessageForErrors()
void MorseCode::checkMessageForErrors (const std::string & message) [private]
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function checks for the errors in the message to be encoded
Parameters
 in message
Returns
[out] void
Precondition
Pre Condition - a string message is passed
Postcondition
Post Condition - throws exception is the message contains chars which are not alpha or whitespace
Bug
Bug No known bugs
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function checks for the errors in the message to be encoded
Parameters
 in message
Returns
[out] void
Precondition
Pre Condition - a string message is passed
Postcondition
Post Condition - throws exception is the message contains chars which are not alpha or whitespace
Bug
Bug No known bugs
using try catch to throw and catch an exception
using for loop to iterate over the message
check if char is not alpha nor whitespace then throw exception
throwing exception
printing the exception
exiting the program
Referenced by encodeMessage().
checkMorseCodeForErrors()
void MorseCode::checkMorseCodeForErrors (const std::string & morseCodeMessage) [private]
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function checks for the errors in the morse code to be decoded
Parameters
 in message
Returns
[out] void
Precondition
Pre Condition - a string morsecodeMessage is passed
Postcondition
Post Condition - throws exception is the morse code contains chars apart from '.' , '_' and '/'
Bug
Bug No known bugs
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function checks for the errors in the morse code to be decoded
Parameters
 in message
Returns
[out] void
Precondition
Pre Condition - a string morsecodeMessage is passed
Postcondition
Post Condition - throws exception is the morse code contains chars apart from '.' , '_' and '/'
Bug
Bug No known bugs
using try catch to throw and catch an exception
using for loop to iterate over the message
check if char '.', '-', or '/' then continue else throw exception
throwing exception
printing the exception
exiting the program
Referenced by decodeMorseCode().
decode()
void MorseCode::decode (const std::string & morseCodeLetter, unsigned int index, Binary_Tree< char > * rootTree) [private]
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function decodes the morse code into a message by traversing through the tree
Parameters
 in morseCodeLetter
 in index
 in rootTree
Returns
[out] void
Precondition
Pre Condition - a string morsecode, an index, and a binary tree is passed
Postcondition
Post Condition - morse code is decoded
Bug
Bug No known bugs
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function decodes the morse code into a message by traversing through the tree
Parameters
 in morseCodeLetter
 in index
 in rootTree
Returns
[out] void
Precondition
Pre Condition - a string morsecode, an index, and a binary tree is passed
Postcondition
Post Condition - morse code is decoded
Bug
Bug No known bugs
storing a char of the morse code
check if the char matches then go to left subtree
storing the left subtree into a variable
recursive calling the func to traverse the tree
check if the char matches then go to right subtree
storing the right subtree into a variable
recursive calling the func to traverse the tree
check if the char matches whitespace then print it
else print the char inside the current node
References decode(), Binary_Tree< Item_Type >::get_data(), Binary_Tree< Item_Type >::get_left_subtree(), and Binary_Tree< Item_Type >::get_right_subtree().
Referenced by decode(), and decodeMorseCode().
decodeMorseCode()
void MorseCode::decodeMorseCode (const std::string & morseCode)
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function decodes the morsecode into message
Parameters
 in morseCode
Returns
[out] void
Precondition
Pre Condition - a string morsecode is passed
Postcondition
Post Condition - morsecode is decoded
Bug
Bug No known bugs
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function decodes the morsecode into message
Parameters
 in morseCode
Returns
[out] void
Precondition
Pre Condition - a string morsecode is passed
Postcondition
Post Condition - morsecode is decoded
Bug
Bug No known bugs
calling func MorseCode::checkMorseCodeForErrors to check for errors in encoded message
creating an object of istringstream class to stream the string into different variables. Takes a string as an argument.
stores morse code of a letter
calling func MorseCode::decode to decode the morse code
References binaryTree, checkMorseCodeForErrors(), and decode().
Referenced by main().
encodeMessage()
void MorseCode::encodeMessage (std::string & message)
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function encodes the message into morse code
Parameters
 in message
Returns
[out] void
Precondition
Pre Condition - a string message is passed
Postcondition
Post Condition - message is encoded
Bug
Bug No known bugs
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function encodes the message into morse code
Parameters
 in message
Returns
[out] void
Precondition
Pre Condition - a string message is passed
Postcondition
Post Condition - message is encoded
Bug
Bug No known bugs
calling MorseCode::checkMessageForErrors to check for errors in the message
creating a variable to store encoded morse code
using a for loop to encode the message
check if the char is whitespace then add a delimiter '/' and a whitespace to it
if the char is in uppercase convert it lowercase as all the tree contains lowercase letters
converting uppercase to lowercase
adding the the morsecode to the string to get a full encoded message
re-assigning message to morse code to help decode the message without returning a string
print the morse code after encoding the message
References checkMessageForErrors(), and morseCodeMap.
Referenced by main().
mapMorseCode()
void MorseCode::mapMorseCode ()
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function read a file then maps the alphabet to its morse code and stores all the alphabet in the binary tree
Parameters
 in void
Returns
[out] void
Postcondition
Post Condition - binary tree is filled with values.
Bug
Bug No known bugs
Module Name: Morse Code Encoder/Decoder
 Author: Faisal Javed
 Date of Creation: 24th November, 2022
 Purpose: the function read a file then maps the alphabet to its morse code and stores all the alphabet in the binary tree
Parameters
 in void
Returns
[out] void
Postcondition
Post Condition - binary tree is filled with values.
Bug
Bug No known bugs
creating an object of input file stream to perform read operations. takes StudentDataCollection.getSecondFileInputName function as a string argument which returns the file name.
Checks if the file is NOT opened then throw an error and stop the program.
throw is a keyword to define custom exceptions. We will
Exceptions
runtime_error exception if the file is unable to open.
creating a variable to store each line from file
while loop to iterate over all the content of file
storing the alphabet
storing the morse code
mapping alphabet and morse code
calling func MorseCoe::addNodeBT to add alphabets to binary tree
closing the file stream
References addNodeBT(), binaryTree, and morseCodeMap.
Referenced by main().
Member Data Documentation
binaryTree
Binary_Tree<char>* MorseCode::binaryTree [private]
BinaryTree pointer object.
Referenced by decodeMorseCode(), mapMorseCode(), and MorseCode().
morseCodeMap
std::unordered_map<char, std::string> MorseCode::morseCodeMap [private]
unordered map variable to contain mapped morse code and alphabet values.
Referenced by encodeMessage(), and mapMorseCode().
The documentation for this class was generated from the following files:
MorseCode.h
MorseCode.cpp